### ISSUE TITLE
cluster.node_stats 

### ISSUE THREAD

**Issue by gcaracuel** [aparo/pyes#462]
Environment: 

  pyes=0.99.5
  ES=1.3.2

When trying to ask for: cluster.node_stats() I'm getting the next error:

 Traceback (most recent call last):
   File "/etc/zabbix/externalscripts/ESzabbix.py", line 47, in <module>
    nodestats = conn.cluster.node_stats()
  File "/usr/lib/python2.7/site-packages/pyes/managers.py", line 630, in node_stats
    return self.conn._send_request('GET', path)
  File "/usr/lib/python2.7/site-packages/pyes/es.py", line 477, in _send_request
    raise_if_error(response.status, decoded)
  File "/usr/lib/python2.7/site-packages/pyes/convert_errors.py", line 85, in raise_if_error
    raise excClass(msg, status, result, request)
pyes.exceptions.IndexMissingException: [_cluster] missing

It seems that "_cluster/nodes/stats" are not longer allowed. It must be "/_nodes/stats"

**Comment by robertwe** [comment]
looks like we got the same on ES 1.7
