### ISSUE TITLE
Invalid error message when a non-integer port is given in the connect string

### ISSUE THREAD

**Issue by ravipra** [aparo/pyes#490]
Invalid error message is given when a non-integer port is given in the connect string.

For example:

conn_str = 'localhost' + ':' + str('abcd')
es = ES(conn_str)

It throws:
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    es = ES(conn_str)
  File "/usr/local/lib/python2.7/dist-packages/pyes/es.py", line 274, in __init__
    self._check_servers()
  File "/usr/local/lib/python2.7/dist-packages/pyes/es.py", line 330, in _check_servers
    raise RuntimeError("Invalid port: \"%s\"" % port)
UnboundLocalError: local variable 'port' referenced before assignment

**Comment by ravipra** [comment]
Fixed by issue 491.
